# Generated by Django 4.2.20 on 2025-03-09 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="related_notes",
            new_name="relation",
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
