version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Zetter_postgres
    restart: always
    environment:
      POSTGRES_USER: zettler_user
      POSTGRES_PASSWORD: zet123
      POSTGRES_DB: zettler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

